services:
  app:
    build:
      context: .
      args:
        - ENVIRONMENT=production
    container_name: chatbot-wsp-app
    expose:
      - "8000"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - chatbot-network

  nginx:
    build:
      context: ./nginx
    container_name: chatbot-wsp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge
