services:
  app:
    build:
      context: .
      args:
        - ENVIRONMENT=production
    container_name: chatbot-wsp-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    stdin_open: true
    tty: true
