services:
  app:
    build:
      context: .
      args:
        - ENVIRONMENT=production
    container_name: chatbot-wsp-app
    expose:
      - "8000"
    volumes:
      - .:/app
    env_file:
      - .env
